ctc_loss_weight: 0.3 # the weight used to combine the CTC loss with the RNNT loss
use_cer: false
ctc_reduction: 'mean_batch'
decoder:
  _target_: nemo.collections.asr.modules.ConvASRDecoder
  feat_in: null
  num_classes: -1
  vocabulary: []
decoding:
  strategy: "greedy"