
name: adamw
lr: 5e-3
# optimizer arguments
betas: [0.9, 0.98]
weight_decay: 1e-3

# scheduler setup
sched:
  name: CosineAnnealing
  # scheduler config override
  warmup_steps: 15000
  warmup_ratio: null
  min_lr: 5e-4