# "default|warprnnt|warprnnt_numba|pytorch|multiblank_rnnt|multiblank_rnnt_pytorch|graph_w_transducer|graph_rnnt|tdt|tdt_pytorch" # default == warprnnt_numba
# default == warprnnt_numba
loss_name: "default"

warprnnt_numba_kwargs:
  # FastEmit regularization: https://arxiv.org/abs/2010.11148
  # You may enable FastEmit to reduce the latency of the model for streaming
  fastemit_lambda: 0.0  # Recommended values to be in range [1e-4, 1e-2], 0.001 is a good start.
  clamp: -1.0  # if > 0, applies gradient clamping in range [-clamp, clamp] for the joint tensor only.