
sample_rate: ${model.sample_rate}
batch_size: 1
shuffle: true
num_workers: 2
max_duration: 30.0
min_duration: 0.5
pin_memory: true
use_start_end_token: false

shard_manifests: false
manifest_filepath: /path/to/test.json

is_tarred: false
shuffle_n: 2048
tarred_audio_filepaths: null
