devices: -1 # number of GPUs, -1 would use all available GPUs
num_nodes: 1
max_epochs: 500
max_steps: -1 # computed at runtime if not set
val_check_interval: 1.0 # Set to 0.25 to check 4 times per epoch, or an int for number of iterations
accelerator: auto
strategy:
  _target_: lightning.pytorch.strategies.DDPStrategy
  gradient_as_bucket_view: true
accumulate_grad_batches: 1
gradient_clip_val: 1.0
precision: bf16-mixed # 16, 32, or bf16 (mixed precisions are also supported)
log_every_n_steps: 10  # Interval of logging.
enable_progress_bar: True
num_sanity_val_steps: 0 # number of steps to perform validation steps for sanity check the validation process before starting the training, setting to 0 disables it
check_val_every_n_epoch: 1 # number of evaluations on validation every n epochs
sync_batchnorm: true
enable_checkpointing: False  # Provided by exp_manager
logger: false  # Provided by exp_manager
benchmark: false # needs to be false for models with variable-length speech input as it slows down training