sample_rate: 16000
compute_eval_loss: false
log_prediction: true
skip_nan_grad: false

model_defaults:
  enc_hidden: ${model.encoder.d_model}
  pred_hidden: 640
  joint_hidden: 640

  tdt_durations: [0, 1, 2, 3, 4]
  num_tdt_durations: 5
