sample_rate: ${model.sample_rate}
batch_size: 1
shuffle: true
num_workers: 2
max_duration: 30.0
min_duration: 0.5
pin_memory: true
use_start_end_token: false
trim_silence: false

# sharded manifests
shard_manifests: false # default to false. no matter missing this.

# # If shard_manifests is true, you can choose one of the following two formats:
# # 1. comma separated
# manifest_filepath: /path/to/shard_1.json,/path/to/shard_2.json,/path/to/shard_3.json,/path/to/shard_4.json
# # 2-1. list with brackets
# mainfest_filepath: ["/path/to/shard_1.json", "/path/to/shard_2.json", "/path/to/shard_3.json", "/path/to/shard_4.json"]
# # 2-2. list with hyphen
# manifest_filepath:
#   - /path/to/shard_1.json
#   - /path/to/shard_2.json
#   - /path/to/shard_3.json
#   - /path/to/shard_4.json
# # 3. brace expansion format
# manifest_filepath: /path/to/shard_{1..4}.json
# # 4. special tags for brace expansion, _OP_ and _CL_
# # _OP_ is for opening brace, and _CL_ is for closing brace.
# manifest_filepath: /path/to/shard__OP_1..4_CL_.json

# If shard_manifests is false, you can only use a single manifest file.
manifest_filepath: /path/to/train.json


# tarred datasets
is_tarred: false # default to false.

# # If is_tarred is true, you should provide a list of tarred audio filepaths.
# # The format is same as the manifest_filepath when shard_manifests is true.
# tarred_audio_filepaths:
#   - /path/to/tarred_audio_1.tar
#   - /path/to/tarred_audio_2.tar

# If is_tarred is true,
shuffle_n: 2048 # default to 0.

# If is_tarred is false, tarred_audio_filepaths should be null.
tarred_audio_filepaths: null

# Bucketing
# Bucketing is valid when using sharded manifests and tarred datasets.
# Bucketing strategy can be one of the following:
# - "fixed_order": 
# - "synced_randomized": 
# - "fully_randomized": 
bucketing_strategy: "synced_randomized"


# # choose one of the following three:
# # Adapted-size bucketing
# # Each bucket has different batch size.
# # the order of the batch size is same as the order of the manifest_filepath and tarred_audio_filepaths.
# bucketing_batch_size: [32, 16, 8, 4]
# # Fixed-size bucketing
# # All bucket have this batch size. 
# bucketing_batch_size: 32 # model.train_ds.batch_size is changed to 1 when using like this.
bucketing_batch_size: null # following model.train_ds.batch_size if null.
