defaults:
  - model: EncDecRNNTBPEModel_with_tdt
  - model/datasets@model.train_ds: train_ds
  - model/datasets@model.validation_ds: validation_ds
  - model/datasets@model.test_ds: test_ds
  - model/tokenizer: tokenizer
  - model/preprocessor: AudioToMelSpectrogramPreprocessor
  - model/spec_augment: SpectrogramAugmentation
  - model/encoder: ConformerEncoder
  - model/decoder: RNNTDecoder
  - model/joint: RNNTJoint
  - model/decoding: greedy_batch
  - model/aux_ctc: aux_ctc
  - model/interctc: interctc
  - model/loss: default
  - model/optim: Adamw-NoamAnnealing
  - trainer: trainer
  - exp_manager: exp_manager

name: "michigety-asr-ko"