defaults:
  - model: EncDecRNNTBPEModel
  - model/datasets@model.train_ds: train_ds
  - model/datasets@model.validation_ds: validation_ds
  - model/datasets@model.test_ds: test_ds
  - model/tokenizer: tokenizer
  - model/preprocessor: AudioToMelSpectrogramPreprocessor
  - model/spec_augment: SpectrogramAugmentation
  - model/encoder: ConformerEncoder
  - model/decoder: RNNTDecoder
  - model/joint: RNNTJoint
  - model/decoding: greedy_batch
  #- model/aux_ctc: aux_ctc
  #- model/interctc: interctc
  - model/loss: tdt
  - model/optim: Adamw-NoamAnnealing
  - trainer: trainer
  - exp_manager: exp_manager
  - _self_

name: "michigety-asr-ko-FastConformer-TDT"
# model size configurations
model:
  model_defaults:
    enc_hidden: ${model.encoder.d_model}
    pred_hidden: 640
    joint_hidden: 640

  encoder:
    d_model: 512
    n_heads: 8
    n_layers: 17
    xscaling: true

  decoder:
    prednet:
      pred_rnnt_layers: 1
